### ISSUE TITLE
No recipe-box User Stories

### ISSUE THREAD

**Issue by 2cb-log** [P1xt/chingu-fcc-speedrun-p1xt#29]
Quickly comparing the "Recipe Box" against other Speedrun challenges, this one seems to be an outlier.  The screenshot of course provides plenty of hints but wondering if the same level of detail on required functionality can be added.

Have not reviewed the code yet, though, so maybe the specs are found there...?

**Comment by P1xt** [comment]
I'm not too worried about it. It looks like I just forgot to copy the user stories back into the readme after I generated the scaffold of the app with Angular. The user stories are actually present in the backup readme here: https://github.com/P1xt/chingu-fcc-speedrun-p1xt/blob/master/data-vis/recipe-box/README_backup.md

And, this was just my private repo for when I personally was running the speed run, the "clean repo" setup for others to run the challenge is here and has all the user stories laid out for you:

https://github.com/P1xt/chingu-fcc-speedrun-challenge

**Comment by 2cb-log** [comment]
Got it.  Thought I had glanced over the backup and didn't see them there, but then I thought I was in the clone-able repo too but wasn't!  Thanks for the clarification and of course the challenges themselves.  Closing.
